# **1 - Criar o banco de dados local com a biblioteca SQLAlchemy.**

In [32]:
import sqlalchemy
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [33]:
# Criando motor
engine = create_engine('sqlite:///:memory:')

In [34]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
database = pd.read_csv(url)
database

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

# **2 - Escrever os dados do arquivo CSV neste banco de dados local.**

In [35]:
database.to_sql('clientes', engine, index=False)

438463

# **3 - Realizar três atualizações no banco de dados:**

*   Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.
*   Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.
*   Criar um novo registro de cliente seguindo as especificações abaixo:

    1. ID_Cliente: 6850985
    2. Idade: 33
    3. Grau_escolaridade: Doutorado
    4. Estado_civil: Solteiro
    5. Tamanho_familia: 1
    6. Categoria_de_renda: Empregado
    7. Ocupacao: TI
    8. Anos_empregado: 2
    9. Rendimento_anual: 290000
    10. Tem_carro: 0
    11. Moradia: Casa/apartamento próprio

In [36]:
# Atualizando o cliente 6840104
with engine.connect() as conexao:
    result = conexao.execute(text('UPDATE clientes SET Rendimento_anual="300000" WHERE ID_Cliente=6840104'))
    conexao.commit()

In [37]:
# Deletando o cliente 5008809
with engine.connect() as conexao:
    result = conexao.execute(text('DELETE FROM clientes WHERE ID_Cliente=5008809'))
    conexao.commit()

In [38]:
# Adicionando o cliente 6850985
with engine.connect() as conexao:
    result = conexao.execute(text(f'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia) VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/apartamento próprio")'))
    conexao.commit()

In [39]:
pd.read_sql("clientes", engine)


ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   
438462     6850985     33         Doutorado       Solteiro                1   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   
438462            Empregado                TI               2   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  
438462          290000.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]